name: Build Kext

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build AppleIntelTGLController
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Verify Xcode Version
        run: xcodebuild -version

      - name: Build Xcode Project
        run: |
          xcodebuild -project AppleIntelTGLController.xcodeproj -scheme AppleIntelTGLController -configuration Release -derivedDataPath build -arch x86_64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
          
      - name: Upload Kext Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AppleIntelTGLController-Kext
          path: build/Build/Products/Release/AppleIntelTGLController.kext
